### ISSUE TITLE
QtQuitButtonDemo1 - connect signals not working

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#1]
QtQuitButtonDemo doesn't work. 
Need proper example for using QtCore.QMetaMethod for sending signals around.

**Comment by dsoronda** [comment]
I need to bind signals from QtButton (clicked) to QtApp (quit)

I tried this :
` // This is from : [Qt documentation](https://wiki.qt.io/How_to_Use_QPushButton)
 //connect(m_button, SIGNAL(released()), this, SLOT(handleButton()));

 Connect(quitButton, "clicked()","quit()");`

**Comment by ddobrev** [comment]
I have actually wrapped Qt signals as C# events. So all you need to do is:

quitButton.Clicked += &lt;your handler&gt;;

**Comment by dsoronda** [comment]
@ddobrev 

Thanks, that fixed this issue.
