### ISSUE TITLE
Reference to QtQuick.Sharp not updated

### ISSUE THREAD

**Issue by ddobrev** [dsoronda/QtSharpDemos#11]
https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/QtSharpDemos.csproj#L51 says that the reference to the binding for QtQuick is still called "QtQuickSharp", it should be now named "QtQuick.Sharp" instead.

**Comment by dsoronda** [comment]
I'll try to update this to latest version soon. Having newborn is not helping.

**Comment by dsoronda** [comment]
Fixed in commit ab77407609d72b0e1e841e1c53e7c7bd87001d53
