### ISSUE TITLE
Exception on handling OnPaintEvent

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#2]
I'm porting this [example](http://zetcode.com/gui/csharpqyoto/painting/).

Currently there is error in PaintDemo class.
I'm not sure how to handle this event in QtSharp.
this is not working :

``` csharp
  PaintEvent += OnPaintEvent;
```

@ddobrev, can you help me with this one?

**Comment by ddobrev** [comment]
Please upload your code (you can attach it here as an archive) and the stack trace. Bear in mind, however, that I am busy at least until the end of the month so unless it's obvious and therefore really quick to fix, it's going to take a while. So please move on to any other examples you want ported when you have sent the information I asked for.

**Comment by dsoronda** [comment]
Hi @ddobrev ,
you can pull this repository and try to run it or try look at [PaintDemo.cs](https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs).
Either way this is what bugs me:

`

```
    public PaintDemo()
    {
        WindowTitle = "Paint Demo";

        var paintEvent = new QPaintEvent(this.Rect);
        // HOW TO ADD ACTION TO PAINT EVENT ????
        this.OnPaintEvent(paintEvent);
        //this.OnPaintEvent += MyPaintEvent; // we need something like this ?

        Resize(250, 150);
        Move(300, 300);
        Show();
    }

    protected override void OnPaintEvent(QPaintEvent e)
    {
        base.OnPaintEvent(e);

        var painter = new QPainter();

        // this is example from Qt site, http://doc.qt.io/qt-5/qtwidgets-widgets-scribble-example.html
        // throws Access Violation exception, "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}
        //var painter2 = new QPainter(this);// throws Access Violation exception

        // this.InitPainter(painter);    // throws Access Violation exception , same as abowe, if commented nothing is drawn on widget

        DrawPatterns(painter);

        painter.End();
    }

    void DrawPatterns(QPainter ptr)
    {
        ptr.SetPen(PenStyle.NoPen);

        ptr.SetBrush(BrushStyle.HorPattern);
        ptr.DrawRect(10, 15, 90, 60);
    }
```

`

**Comment by ddobrev** [comment]
Thanks. It's not a quick one, I'm afraid, so please move on, I'll check it whenever I have time.

**Comment by ddobrev** [comment]
My last remark was about the crash but I think there are two problems here. Are you saying that PaintEvent is never raised?

**Comment by dsoronda** [comment]
I'll try to be more specific.
If I comment out this 

```
        ///var paintEvent = new QPaintEvent(this.Rect);
        ///this.OnPaintEvent(paintEvent);
        //this.OnPaintEvent += MyPaintEvent; // we need something like this ?
```

```
// this one is still called
protected override void OnPaintEvent(QPaintEvent e)
    {
        base.OnPaintEvent(e);
        // this is example from Qt site, http://doc.qt.io/qt-5/qtwidgets-widgets-scribble-example.html
        // next line throws Access Violation exception, "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}
      var painter = new QPainter(this); // in this case this is PainterDemo class(inherited from QWidget)
     DrawPatterns(painter);
        painter.End();
    }
```

**Comment by ddobrev** [comment]
@dsoronda what I mean is - is MyPaintEvent called if you have uncommented

```
this.OnPaintEvent += MyPaintEvent;
```

?

**Comment by dsoronda** [comment]
@ddobrev 
I update project code, check it on this link [PaintDemo](https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs)

**Comment by ddobrev** [comment]
A compilation error, I understand. Thank you. I'll let you know about any developments.

**Comment by ddobrev** [comment]
@dsoronda the problem is that you have copied the code from the Qyoto example without checking the signature of the event. You miss a parameter in your handler. Use the auto-completion of your IDE to generate a correct handler and see its signature.

**Comment by dsoronda** [comment]
@ddobrev 
I'm not sure what signature do you mean?

```
   // this code generates Visual studio 2015 for override OnPaintEvent 
    protected override void OnPaintEvent(QPaintEvent @event)
        {
            base.OnPaintEvent(@event);
        }
```

I also updated my PaintDemo example based on  Qyoto example, still got exception on calling :
`var painter = new QPainter(this);`

**Comment by ddobrev** [comment]
@dsoronda never mind, my mistake. I can see you actually have the correct line at https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs#L23 . Could you please tell me if MyPaintEvent is called?

**Comment by dsoronda** [comment]
@ddobrev 
Yes, MyPaintEvent is called.

**Comment by ddobrev** [comment]
Excellent, so we have just one bug after all. What I am certain of is that the crash you get in MyPaintEvent and in your OnPaintEvent override is the same bug. What I am almost certain of is the cause for it but I'll really have to fix it later on.
Thank you for your report and the time you took to make the situation clear to me. I won't bother you about this one any more.

**Comment by dsoronda** [comment]
@ddobrev , feel free to ask if you have any more questions, I don't mind.
Lets make QtSharp even better and spread it to the world :)

Just let me know when you fix this issue. And thank you for QtSharp.

**Comment by ddobrev** [comment]
@dsoronda I am really happy to let you know that I have finally fixed the problem. Please get the new release from https://github.com/ddobrev/QtSharp/releases/tag/0.6.0 .

**Comment by dsoronda** [comment]
Closing one as FIXED :)

@ddobrev  Thank you for this new release.

**Comment by ddobrev** [comment]
You're welcome. :)
I assume you'd now be quick to port the remaining old Qyoto examples so in case you need more ideas to develop, I have a suggestion. Just let me know.

**Comment by ddobrev** [comment]
Also, now that it works, could you please delete any comments which state it doesn't, such as https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs#L19 , https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs#L38 or https://github.com/dsoronda/QtSharpDemos/blob/master/source/QtSharpDemos/GuiExample/PaintDemo.cs#L51 ?

**Comment by dsoronda** [comment]
I deleted those comments.
