### ISSUE TITLE
Load and display Window/Control from QML file

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#3]
I have new issue with load and display of QML file from QtSharp but I not sure how to do it properly.
Does anyone know proper C++ example ?

I tried 2 different approach and both gives me empty window :

[QuickViewDemo](QtSharpDemos/source/QtSharpDemos/GuiExample/QuickViewDemo.cs) and [QmlDemo](QtSharpDemos/source/QtSharpDemos/GuiExample/QmlDemo.cs)

**Comment by ddobrev** [comment]
I have seen an example with QtQuick work but I cannot remember what the problem was before it did. However, you can check it yourself - https://github.com/grbd/QtSharp.TestApps/tree/master/TestApps/QtQuick/BasicLayouts1_CS.

**Comment by dsoronda** [comment]
@ddobrev  , thanks for example.

I added new QQmlApplicationEngineDemo example.
