### ISSUE TITLE
QImage.Copy bug

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#5]
QImage.Copy() uses default Rect for parameter and creates confusion since user expects exact copy of image not QImage with QSize(1,1)

``` csharp
        public static QImage ConvertToGrayScale ( QImage originalImage ) {
            //var newImage = originalImage.Copy(); // this is misleading bug!
            // new image is QSize (1,1) instead exact copy of original image
            var newImage = originalImage.Copy(originalImage.Rect); // this should be used in Copy() implementation
            return newImage;
        }
```

**Comment by ddobrev** [comment]
The documentation says that by default the entire image should be copied which means the QRect I pass as the default parameter is not a null rectangle contrary to what I had thought. I'll definitely check it.

**Comment by dsoronda** [comment]
@ddobrev , you pass default QRect with QSize(1,1) instead originalImage.Rect

**Comment by ddobrev** [comment]
@dsoronda yes, this is apparently what happens even though I use new QRect() as the default parameter. I have a good idea what the problem might be so I'll let you know as soon as it's fixed.

**Comment by ddobrev** [comment]
@dsoronda this one is fixed by the new release, https://github.com/ddobrev/QtSharp/releases/tag/0.6.1 .

**Comment by dsoronda** [comment]
@ddobrev Thank you for the fix.

This one is closed now.
