### ISSUE TITLE
QColor.Gray missing implementation

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#6]
@ddobrev, QtSharp is missing QColor.Gray implementation.

``` csharp
                    // [QtSharp - missing implementation of qGray](http://doc.qt.io/qt-4.8/qcolor.html#qGray)
                    // int gray = color.Gray;

                    // Current workaround
                    // The gray value is calculated using the formula ( r * 11 + g * 16 + b * 5 ) / 32.
                    int gray = ((color.Red *11) + (color.Green * 16) + (color.Blue * 5)) /32;
```

**Comment by ddobrev** [comment]
qGray is not a member of the QColor class, it's directly placed in the header instead. We map such functions (free functions) to static methods of an artificial class named after the header. In this case what you're looking for is "qcolor.qGray".
The fact that you have filed this bug shows you're confused with the API which might hint at some room for improvement. I'll think about it in time but after all of your other issues because they are more important.

**Comment by dsoronda** [comment]
@ddobrev , maybe we are talking about 2  different Gray ?
This is from QColor metadata

``` csharp
// Finally, the qAlpha() function returns the alpha
//     component of the provided QRgb, and the qGray() function calculates and return
//     a gray value based on the given value.
```

So, i was expecting that color.Gray is valid  property 

``` csharp
      int gray = color.Gray; // get calculated gray value from Qt
     // The gray value is calculated using the formula ( r * 11 + g * 16 + b * 5 ) / 32.

     int alpha = color.Alpha; // Get Alpha value from rgbA
```

We could use above formula to create workaround property for QtSharp ?

As for 

> "qcolor.qGray"

I can't find it ?

**Comment by ddobrev** [comment]
My mistake, it's actually qrgb.QGray. Finding these functions is definitely a problem, I'll see what I can do in the long term.

**Comment by ddobrev** [comment]
About that "Gray" property, I am afraid I have no idea where you got it from. As far as I know, you are porting the examples from Zetcode and I cannot see such a property at http://zetcode.com/gui/csharpqyoto/paintingII/ , it's also missing from the old C# bindings for Qt by the name of Qyoto which are used in Zetcode. Could you please point me to the original Qt member? Please bear in mind that properties are originally parameterless non-void functions.

**Comment by ddobrev** [comment]
I've just tried qrgb.QGray and it works.
