### ISSUE TITLE
QtSharp - missing QRgba impelentation

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#7]
@ddobrev QtSharp is missing implementation of QRgba ?

[Ref: QRgb QColor::rgba() const](http://doc.qt.io/qt-5/qcolor.html#rgba)

``` csharp
                   var color = originalImage.PixelColor ( point );
                    UInt32 pixel = originalImage.Pixel(point);
                    // how to convert pixel to QRgba ??
                    //QRgba rgbaPixel = (QRgba) pixel;
```

**Comment by ddobrev** [comment]
QRgb is some strange typedef which means that we most probably have an unsupported type here. I'll see if we can support it but this cannot always be done, it depends on the type.

**Comment by dsoronda** [comment]
@ddobrev 
We could use Class/Struct QRgb as helper class and add few properties to it ?
Something like 

```
QRgba rgba = ToQRgba(int32 color);
rgba.Int = color;
rgba.R = 234; // Red component; // get {( return (color & 0xFF000000 ) >> 24) ; set { Int = ( value <<24 & Int ) }} 
rgba.B = 16; // Blue component;  // get {( return (color & 0x00FF0000 ) >> 24) ; set { Int = ( value <<24 & Int ) }} 
... etc
int32 color = rgba.ToInt32();

```

**Comment by ddobrev** [comment]
@dsoronda thank you for the suggestion. However, in C++#, the tool which generates Qt#, we try to automate as much generation as possible. So I would first have to see what this type is and then explore ways of wrapping it without manual effort. Please move on with the other examples and don't worry about this one.

**Comment by ddobrev** [comment]
@dsoronda QRgb (http://doc.qt.io/qt-5/qcolor.html#QRgb-typedef) is simply a typedef for uint, there's no structure involved. Could you please show me the original code so that I can see where exactly this came from?

**Comment by ddobrev** [comment]
@dsoronda I am going to generate a new release so that https://github.com/dsoronda/QtSharpDemos/issues/5 is fixed. Could you please tell me if this, and the Gray property, are real problems? If so, I'd rather fix them and include them in the release, otherwise I can start generating it immediately.

**Comment by dsoronda** [comment]
@ddobrev 
This is not critical issue and I managed to make demo work.

And for QRgba, above example is just my suggestion how to wrap int32 into RGBA class so I could easily manipulate just a part of it (lets say Red part) and get ti back as int32.

This could be just additional extension to QRgba or something.
I don't know is it possible for you to generate QRgba as partial class so we could extend it that way ?

I was thinking something like this:

``` csharp

    /// <summary>
    /// This class is partial so we could extend QRgba with additional properties
    /// </summary>
    public partial class QRgba {
        // An ARGB quadruplet on the format #AARRGGBB, equivalent to an unsigned int.
        public UInt32 ColorBits { get; set; } = 0x00000000;

        public Byte Alpha {
            get { return ( Byte ) ( ( ColorBits & 0xFF000000 ) >> 24 ); }
            set {
                var cleared = ColorBits & 0x00FFFFFF;
                ColorBits = cleared ^ ( ( ( UInt32 ) value ) << 24 ); // xor Alpha values into to 8 bits
            }
        }

        public Byte Red {
            get { return ( Byte ) ( ( ColorBits & 0x00FF0000 ) >> 16 ); }
            set {
                var cleared = ColorBits & 0xFF00FFFF;
                ColorBits = cleared ^ ( ( ( UInt32 ) value ) << 16 ); // xor Red values
            }
        }
        public Byte Green {
            get { return ( Byte ) ( ( ColorBits & 0x0000FF00 ) >> 8 ); }
            set {
                var cleared = ColorBits & 0xFFFF00FF;
                ColorBits = cleared ^ ( ( ( UInt32 ) value ) << 8 ); // xor Green values
            }
        }
        public Byte Blue {
            get { return ( Byte ) (  ColorBits & 0x000000FF  ); }
            set {
                var cleared = ColorBits & 0xFFFFFF00;
                ColorBits = cleared ^ ( ( UInt32 ) value ); // xor Blue values
            }
        }

        public QRgba ( UInt32 colorBits ) {
            this.ColorBits = colorBits;
        }

        public static QRgba ToQRgba ( UInt32 colorBits) => new QRgba ( colorBits );
    }

// or this could be simple Class to manage colors of 
     public  class Rgba {  /// ... code from above 
}
```

**Comment by ddobrev** [comment]
I understand, you want an enhancement to the bindings. Do you know what the standard Qt way of doing the same is?
As a side note, #5 is more problematic than I thought so I might have to finish it tomorrow or even later.

**Comment by ddobrev** [comment]
I can see there actually is a standard way - using the other functions from qrgb: QRed, QBlue, etc. See the Qt documentation, for example http://doc.qt.io/qt-5/qcolor.html#qAlpha . You just pass your uint/QRgba and it will work. I understand you'd like it more object oriented. Unfortunately Qt# is, as you've seen, not particularly stable yet and I would really like everything standard to work before I start thinking about custom extensions.

**Comment by dsoronda** [comment]
I'll leave example code in project for some future.
