### ISSUE TITLE
QColor missing IDisposable ?

### ISSUE THREAD

**Issue by dsoronda** [dsoronda/QtSharpDemos#8]
@ddobrev
When I run this thru memory profiler (VS 2015 Community edition) there is a bunch of undisposed QColors on HEAP after I call Paint_GrayscaleImage.ConvertToGrayScale method.

``` csharp
                    // QColor is not disposed !!!
                    // Memory profiler shows a bunch of IDictionary <QColors> on HEAP
                    newImage.SetPixelColor ( point, new QColor ( gray, gray, gray, alpha ) ); 
```

**Comment by ddobrev** [comment]
Do you mean that QColor does not implement IDisposable or that it's not automatically called? The latter is true because we haven't added finalisers (managed destructors) yet, I'll do it as soon as possible.

**Comment by dsoronda** [comment]
Problem is that after this line is executed 

``` csharp
newImage.SetPixelColor ( point, new QColor ( gray, gray, gray, alpha ) ); 
```

QColor is not GCed and it stays on HEAP so we have memory leak.

I'll try to create better example for this.

**Comment by ddobrev** [comment]
@dsoronda I should explain a little more. The managed objects are collected, the native aren't. So far Qt# relies on manual memory management which means each allocated object must be destroyed by calling its Dispose method. Otherwise any Qt objects are going to leak until we have added managed destructors, as I said above.
In your case, just call Dispose on each QColor and leaks will stop.

**Comment by dsoronda** [comment]
@ddobrev 
I changed code to this : 

``` csharp
// force Dispose
 using ( var qColor = new QColor ( gray, gray, gray, alpha ) ) {
                        newImage.SetPixelColor ( point, qColor );
}
```

Still have like 900k of QColor objects on HEAP taking about 40 MBs of RAM.
Maybe I'm missing something?

**Comment by ddobrev** [comment]
Please try also disposing of:

```
var color = originalImage.PixelColor ( point );
```

**Comment by dsoronda** [comment]
@ddobrev 
Yeah, that fixes memory leak. Thanks. I completly forgot for that one.

**Comment by ddobrev** [comment]
Excellent. I'll let you know when we have managed destructors so you'll be able to test with and without, and most probably simplify your code.
